version: '3.5'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  frontend:
    image: frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:      
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REQUEST_ORIGIN=http://localhost
    depends_on: 
      - postgres
  redis:
    image: redis
    volumes:
      - ./database/redis:/data
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
