version: '3.5'

services:
  simple-web-app:
    image: devopsdockeruh/simple-web-service
    build: .
    volumes: 
      - ./text.log:/usr/src/app/text.log
    ports:
      - 8080:8080
    container_name: simple-web
    command: server