version: '3.5'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  frontend:
    image: frontend
    ports:
      - 5000:5000
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:      
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
    depends_on: 
      - postgres
  redis:
    image: redis
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
