version: '3.8'

services:
  mlfrontend:
    build: ./ml-frontend
    ports:
      - 3000:3000
    depends_on:
      - mlbackend
  mlbackend:
    build: ./ml-backend
    ports:
      - 5000:5000
    volumes:
      - ./model:/src/model
    depends_on: 
      - mltraining
  mltraining:
    build: ./ml-training
    volumes:
      - ./imgs:/src/imgs
      - ./model:/src/model
      - ./data:/src/data